spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/rndayala/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "file:///C://config"
          #search-locations: "classpath:/config"
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true